# Release workflow
name: Release
on:
    push:
        branches:
            - '!master'
            - '*-[0-9]+*'
        tags:
            - '*-[0-9]+*'
jobs:
    release_job:
        name: Release Job
        runs-on: ubuntu-latest
        steps:
            - name: Setup workspace
              uses: dynod/repo-checkout@1.2.0
              with:
                  url: https://github.com/dynod/workspace.git
                  manifest: fromRef
                  env: OUTPUT_ROOT=/github/workspace/out
            - name: Run tests
              uses: dynod/call-make@1.2.0
              with:
                  target: tests
                  env: OUTPUT_ROOT=/github/workspace/out
            - name: Archive Python distribution
              uses: actions/upload-artifact@v1
              with:
                  name: dist
                  path: out/artifacts/python
            - name: Archive flake8 report
              uses: actions/upload-artifact@v1
              with:
                  name: flake8 report
                  path: out/flake-report
            - name: Archive coverage report
              uses: actions/upload-artifact@v1
              with:
                  name: coverage report
                  path: out/coverage-report
            - name: Archive tests report
              uses: actions/upload-artifact@v1
              with:
                  name: tests logs and report
                  path: out/tests

            # Publish to Pypi (only on tags push)
            - name: Publish package
              if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
              uses: pypa/gh-action-pypi-publish@v1.1.0
              with:
                  user: __token__
                  password: ${{ secrets.pypi_password }}
                  packages_dir: out/artifacts/python
